facultyeval/accounts/urls.py
from django.urls import path, reverse_lazy
from .views import Login, Register, logoutUser, PassResetView
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", logoutUser, name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("password-reset/", 
        PassResetView.as_view(
            template_name="accounts/reset_password.html",
            success_url=reverse_lazy("accounts:password_reset_done"),
            html_email_template_name="accounts/password_reset.html",
            email_template_name="accounts/password_reset.html"),
        name="password_reset"
    ),
    path("password-reset-done/", 
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/reset_password_done.html"), 
        name="password_reset_done"
    ),
    path("password-reset-confirm/<uidb64>/<token>/", 
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/reset_password_confirm.html", 
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm"
    ),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
]

facultyeval/administrator/urls.py
from django.urls import path
from .views import *

app_name = "administrator"
urlpatterns = [
    path('list_of_members/export_pdf/', GeneratePdf.as_view(), name="export_members_pdf"), 
    # path("list_of_members/export_pdf", export_members_pdf, name='export_members_pdf'),
    path("list_of_members/export", export_members_csv, name='export_members_csv'),
    path('', Dashboard.as_view(), name="dashboard"),
    path('about/', About, name="about"),
    path('list_of_members/', ListOfMembers, name="list_of_members"),
    path('profile/', Profile, name="profile"),
    path("profile/edit/", EditProfile.as_view(), name="edit_profile"),
    path('delete-member/<int:ID>/', DeleteMember, name="delete_member"),
    path("view-profile-member/<int:ID>/", ViewMemberProfile, name="view_profile_member"),
    path("school-year/", SchoolYearView.as_view(), name="school_year"),
    path("school-year/delete/<int:ID>/", DeleteSchoolYear, name="delete_school_year"),
    path("school-year/new/", NewSchoolYear.as_view(), name="new_school_year")
]

facultyeval/aiv/urls.py
from django.urls import path
from .views import *

app_name = "aiv"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_aiv_pdf'),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export", export_aiv_csv, name='export_aiv_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteAIVCriterion, name="delete_aiv_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-aiv-rating/<int:ID>", DeleteAIVRating, name="delete_aiv_rating"),
    path("<slug:SEM>/<slug:SY>/aiv-rating-entry/", AIVRatingEntry.as_view(), name="aiv_rating_entry"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_aiv_eval_scores"),
    path("<slug:SEM>/<slug:SY>/new-aiv-evaluation/<int:ID>", NewAIVEvaluation, name="new_aiv_evaluation"),
    path("<slug:SEM>/<slug:SY>/aiv-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/canvas/urls.py
from django.urls import path
from .views import *

app_name = "canvas"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<str:MG>/<slug:SY>/export_pdf", GeneratePdf.as_view(), name='export_lms_pdf'),
    path("<slug:SEM>/<str:MG>/<slug:SY>/export", export_lms_csv, name='export_lms_csv'),
    path("<slug:SEM>/<str:MG>/<slug:SY>/", Index.as_view(), name="index"),
    path("evaluation-form-entry/", CreateEval.as_view(), name="eval_entry"),
    path("edit-evaluation/<int:ID>/", EditEval.as_view(), name="edit_eval"),
    path("delete-evaluation/<int:ID>/", DeleteEval, name="delete_eval")
]

facultyeval/facultyeval/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("member.urls")),
    path('administrator/', include("administrator.urls")),
    path('administrator/hr/', include("hr.urls")),
    path('administrator/canvas/', include("canvas.urls")),
    path('administrator/aiv/', include('aiv.urls')),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facultyeval/hr/urls.py
from django.urls import path
from .views import *

app_name = "hr"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_hr_pdf'),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export", export_hr_csv, name='export_hr_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteHRCriterion, name="delete_hr_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-hr-rating/<int:ID>", DeleteHRRating, name="delete_hr_rating"),
    path("<slug:SEM>/<slug:SY>/hr-rating-entry/", HRRatingEntry.as_view(), name="hr_rating_entry"), # <- This might not be used anymore
    path("<slug:SEM>/<slug:SY>/new-hr-evaluation/<int:ID>", NewHREvaluation, name="new_hr_evaluation"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_hr_eval_scores"),
    path("<slug:SEM>/<slug:SY>/hr-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/administrator/models.py
from django.db import models
from accounts.models import Member

# Create your models here.
class SchoolYear(models.Model):
    school_year = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.school_year}"

class ActivityLogs(models.Model):
    ADDED = 'Added'
    DELETED = 'Deleted'
    UPDATE = 'Update'
    CHANGE_CHOICES = [
        (ADDED, 'Added'),
        (DELETED, 'Deleted'),
        (UPDATE, 'Update')
    ]
    LMS = 'LMS'
    HR = 'HR'
    AIV = 'AIV'
    EVAL_CHOICES = [
        (LMS, 'LMS'),
        (HR, 'HR'),
        (AIV, 'AIV')
    ]
    member = member = models.ForeignKey(Member, on_delete=models.CASCADE)
    date_log = models.DateTimeField(auto_now=True)
    activity_log = models.CharField(max_length=200, choices=CHANGE_CHOICES)
    eval_log = models.CharField(max_length=200, choices=EVAL_CHOICES)
    def __str__(self):
        return f"{self.activity_log} evaluation on user {self.member} in {self.eval_log}. [{self.date_log}]"

facultyeval/administrator/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import *

class SchoolYearForm(ModelForm):

    class Meta:

        model = SchoolYear
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SchoolYearForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({"name": field, "class": "form-control"})

class EditUserForm(ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({"class": "form-control"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control"})
        self.fields["email"].widget.attrs.update({"class": "form-control"})

facultyeval/administrator/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from administrator.decorators import admin_only
from administrator.models import ActivityLogs, SchoolYear
from canvas.models import Member
from django.contrib import messages
from .forms import *
from django.http import HttpResponse
import csv
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import View
from django.template.loader import render_to_string
from django.conf import settings
import os

# Create your views here.
class Dashboard(View):
    
    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        logs = ActivityLogs.objects.all()
        return render(request, template_name="administrator/dashboard.html", context={"logs": logs})

@login_required(login_url="accounts:login")
@admin_only
def About(request):
    return render(request, template_name="administrator/about.html", context={})

@login_required(login_url="accounts:login")
@admin_only
def ListOfMembers(request):
    members = Member.objects.all()
    return render(request, template_name="administrator/listofmembers.html", context={"members": members})

@login_required(login_url="accounts:login")
@admin_only
def Profile(request):
    return render(request, template_name="administrator/profile.html", context={})

@login_required(login_url="accounts:login")
@admin_only
def DeleteMember(request, ID):
    member = Member.objects.filter(id=ID)
    if member.exists():
        member.first().user.delete()
    return redirect("administrator:list_of_members")

@login_required(login_url="accounts:login")
@admin_only
def ViewMemberProfile(request, ID):
    member = Member.objects.filter(id=ID)
    if member.exists():
        cntx_user = member.first().user
        return render(request, template_name="administrator/viewmemberprofile.html", context={"cntx_user": cntx_user})
    return redirect("/")

class SchoolYearView(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        school_years = SchoolYear.objects.all()
        form = SchoolYearForm()
        context = {
            "data": school_years,
            "form": form
        }
        return render(request, template_name="administrator/schoolyear.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request):
        form = SchoolYearForm(request.POST)
        if form.is_valid():
            SY = form.save(commit=False)
            school_year = form.cleaned_data.get("school_year")
            SY.school_year = SY.school_year.replace(" ", "-")
            if SchoolYear.objects.filter(school_year=school_year).exists():
                messages.error(request, "School year already exist!")
                return redirect("administrator:new_school_year")
            SY.save()
            messages.success(request, "School year has successfully added!")
            return redirect("administrator:school_year")
        messages.error(request, "Invalid input!")
        return redirect("administrator:new_school_year")

class NewSchoolYear(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        form = SchoolYearForm()
        context = {
            "form": form
        }
        return render(request, template_name="administrator/schoolyearform.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request):
        form = SchoolYearForm(request.POST)
        if form.is_valid():
            SY = form.save(commit=False)
            school_year = form.cleaned_data.get("school_year")
            if SchoolYear.objects.filter(school_year=school_year).exists():
                messages.error(request, "School year already exist!")
                return redirect("administrator:new_school_year")
            SY.save()
            messages.success(request, "School year has successfully added!")
            return redirect("administrator:school_year")
        messages.error(request, "Invalid input!")
        return redirect("administrator:new_school_year")

@login_required(login_url="accounts:login")
@admin_only
def DeleteSchoolYear(request, ID):
    school_year = SchoolYear.objects.filter(id=ID)
    if school_year.exists():
        school_year.delete()
        messages.success(request, "School year has successfully deleted!")
    else:
        messages.error(request, "Error encountered deleting the school year")
    return redirect("administrator:school_year")

@login_required(login_url="accounts:login")
@admin_only
def export_members_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="registered_faculty_members.csv"'
    writer = csv.writer(response)
    writer.writerow(["List of Registered Faculty Members"])
    members = Member.objects.all()
    for member in members:
        writer.writerow([member])
    return response

def html_to_pdf(template_src, context_dict={}):
     template = get_template(template_src)
     html  = template.render(context_dict)
     result = BytesIO()
     pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
     if not pdf.err:
         return HttpResponse(result.getvalue(), content_type='application/pdf')
     return None

class GeneratePdf(View):
    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, *args, **kwargs):

        data = Member.objects.all()
        value = settings.BASE_DIR
        temp = os.path.join(value, "administrator", "templates", "administrator", "temp.html")
        open(temp, "w+").write(render_to_string('administrator/listofmembers_temp.html', {'data': data}))
         
        # getting the template
        pdf = html_to_pdf('administrator/temp.html')
         
        # rendering the template
        return HttpResponse(pdf, content_type='application/pdf')

class EditProfile(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        user_form = EditUserForm(instance=request.user)
        context = {
            "user_form": user_form
        }
        return render(request, template_name="administrator/edit_profile.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request):
        user_form = EditUserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
        return redirect("administrator:profile")

facultyeval/administrator/templates/administrator/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.css"/>
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    </head>
    <body>
        <div class="container-fluid" style="position: absolute; padding-left: 0rem;">
            <div class="row">
                <!-- Sidebar Navigation -->
                <div class="col-auto" style="padding-right: 0rem;">
                    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px; height: 100vh; position:fixed;">
                        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                          <span class="fs-4">Faculty Evaluation</span>
                        </a>
                        <hr>
                        <ul class="nav nav-pills flex-column mb-auto">
                            <li class="nav-item">
                                <a href="{% url 'administrator:dashboard' %}" class="nav-link {% block nav_item_dashboard %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/speedometer.svg'%}" /> 
                                Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                              <a href="{% url 'administrator:list_of_members' %}" class="nav-link {% block nav_item_listofmembers %}{% endblock %} text-white">
                                <img src = "{% static 'img/bootstrap/person-lines-fill.svg'%}" />
                                List of Members
                              </a>
                            </li>
                            <li class="nav-item">
                              <a href="{% url 'administrator:school_year' %}" class="nav-link {% block nav_item_school_year %}{% endblock %} text-white">
                                <img style="filter:invert(100%);" src="{% static 'img/bootstrap/clock-fill.svg'%}" /> 
                                School Year
                              </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'hr:redirect_index' %}" class="nav-link {% block nav_item_hr %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/journals.svg'%}" />
                                  HR
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'aiv:redirect_index' %}" class="nav-link {% block nav_item_aiv %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/clipboard-data-fill.svg'%}" />
                                  AIV
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'canvas:redirect_index' %}" class="nav-link {% block nav_item_canvas %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/mortarboard-fill.svg'%}" /> 
                                  LMS (Canvas)
                                </a>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown">
                            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                              <img src="{% static 'img/admin.png' %}" alt="" width="32" height="32" class="rounded-circle me-2">
                              <strong>{{user.username}}</strong>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                              <li><a class="dropdown-item" href="{% url 'administrator:profile' %}"> <img src = "{% static 'img/bootstrap/person-circle.svg'%}" /> Profile</a></li>
                              <li><a class="dropdown-item" href="{% url 'administrator:about' %}"> <img src = "{% static 'img/bootstrap/person-workspace.svg'%}" /> About</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"><img src = "{% static 'img/bootstrap/box-arrow-right.svg'%}" /> Sign out</a></li>
                            </ul>
                          </div>
                    </div>
                </div>
                <!-- Content -->
                <div class="col" style="margin-left: 280px;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <!-- Footer -->
            {% include 'administrator/footer.html' %}
        </div>
        <!-- JS Scripts -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% block javascript %}
        {% endblock %}
        <!-- <script src="{% static 'css/sidebar.css' %}"></script> -->
    </body>
</html>

facultyeval/administrator/templates/administrator/dashboard.html
{% extends 'administrator/base.html' %}
{% block title %}Dashboard{% endblock %}
{% block nav_item_dashboard %}active{% endblock %}
{% block content %}
{% load static %}
<div class="row align-items-center" style="min-height: 100vh; background-color:azure;">
    <div class="col d-flex justify-content-center">
        <div class="container">
            <div class="row my-5">
                <h4 class="text-left">Welcome {{user.username}}!</h4>
                <!-- Display messages from the server -->
                <div class="col">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                                {% if message.tags == 'error' %}<strong>Error Encountered!</strong><br>{% endif %}
                                {{message}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video1" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/HR.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">HR Evaluation</h5>
                            <p class="card-text">Navigate to HR panel to evaluate a faculty.</p>
                            <a href="{% url 'hr:index' SEM='1st-Sem' SY='2021-2022' %}" class="btn btn-primary">Go to HR</a>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video2" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/AIV.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">AIV Evaluation</h5>
                            <p class="card-text">Navigate to AIV panel to evaluate a faculty.</p>
                            <a href="{% url 'aiv:index' SEM='1st-Sem' SY='2021-2022' %}" class="btn btn-primary">Go to AIV</a>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video3" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/LMS.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">LMS Evaluation</h5>
                            <p class="card-text">Navigate to LMS panel to evaluate a faculty.</p>
                            <a href="{% url 'canvas:index' SEM='1st-Sem' MG='MG1' SY='2021-2022' %}" class="btn btn-primary">Go to LMS</a>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Start of data table -->

            <div class="row my-5">
                <hr>
                <h5 class="text-left">Activity logs</h5>
                <table class="table table-hover" id="myTable">
                    <thead class="table-primary">
                        <th class="text-center" scope="col">ID</th>
                        <th class="text-center" scope="col">Status</th>
                        <th class="text-center" scope="col">User</th>
                        <th class="text-center" scope="col">Evaluation</th>
                        <th class="text-center" scope="col">Date/Time</th>
                    </thead>
                    <tbody>
                        {% for log in logs %}
                            <tr scope="row">
                                <td class="text-center" scope="col" style="width: 10%;">{{log.id}}</td>
                                <td class="text-center" scope="col" style="width: 20%;">{{log.activity_log}}</td>
                                <td class="text-center" scope="col" style="width: 25%;">{{log.member}}</td>
                                <td class="text-center" scope="col" style="width: 20%;">{{log.eval_log}}</td>
                                <td class="text-center" scope="col" style="width: 25%;">{{log.date_log}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script>
	$(document).ready(function(){
		$('#myTable').DataTable();
	});
</script>
<script>
    // Getting video element using jQuery
    var video1 = $("#video1");
    var video2 = $("#video2");
    var video3 = $("#video3");
    // Check if video is ready to play
    $(video1).on('canplay', function () {
        $(video1).mouseenter(function () {
            $(this).get(0).play();
        })
    });
    $(video2).on('canplay', function () {
        $(video2).mouseenter(function () {
            $(this).get(0).play();
        })
    });
    $(video3).on('canplay', function () {
        $(video3).mouseenter(function () {
            $(this).get(0).play();
        })
    });    
</script>
{% endblock %}

facultyeval/administrator/templates/administrator/footer.html
<div class="row">
    <div class="col" style="margin-left: 280px; padding-right: 0rem;">
      <footer class="page-footer" style="z-index: 0; background-color: black; bottom: 0;">
        <div class="footer-copyright py-2 text-center text-white" style="font-size: 14px;">
          © 2022 | Developed by:<br>
          <span style="font-size: 10px;">JAMES JOSHUA BALLES | ZEUS JAMES BALTAZAR | JHOLET MAE BOTONA | CYNNA MAE CREBELLO | CHRISTIAN DALE DELA CRUZ | IAN GABRIEL MARQUEZ | RON RASL PARMAN | FRANCIS GENER PENULIAR</span>
        </div>
      </footer>
    </div>
</div>

facultyeval/administrator/templates/administrator/listofmembers.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %}List of Members{% endblock %}
{% block nav_item_listofmembers %}active{% endblock %}
{% block content %}
<div class="container" style="padding: 40px; min-height: 100vh;">
    <div class="row" style="margin-bottom: 20px;">
        <h3 class="text-center">LIST OF REGISTERED FACULTY MEMBERS</h3>
        <hr>
    </div>
    <div class="row" style="margin-bottom: 20px;">
        <!-- Export buttons (Not implemented yet) -->
        <div class="col d-flex justify-content-start">
            <a href="{% url 'administrator:export_members_pdf' %}" class="btn btn-warning" style="margin-right: 10px;">
                PDF
            </a>
            <a href="{% url 'administrator:export_members_csv' %}" class="btn btn-success">
                CSV
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-hover" id="myTable">
                <thead class="table-success">
                    <th class="text-center" scope="col">FACULTY MEMBER</th>
                    <th class="text-center" scope="col">DATE AND TIME JOINED</th>
                    <th class="text-center">ACTIONS</th>
                </thead>
                <tbody>
                    {% for member in members %}
                        <tr scope="row">
                            <td class="text-center" scope="col">
                                <img src="{% if member.image != '' %}/media/{{member.image}}{% else %}{% static 'img/profile_default.png' %}{% endif %}" class="rounded-circle" alt="" width="32" height="32">
                                {{member.user.last_name}}, {{member.user.first_name}}{% if member.middle_name != "" %}, {{ member.middle_name }}{% endif %}
                            </td>
                            <td class="text-center" scope="col">{{member.user.date_joined}}</td>
                            <td class="text-center" scope="col">
                                <a href="{% url 'administrator:view_profile_member' ID=member.id %}" class="btn" style="background-color: lightblue;">
                                    <img id="user-icon" src="{% static 'img/bootstrap/folder2-open.svg' %}">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}