facultyeval/aiv/urls.py
from django.urls import path
from .views import *

app_name = "aiv"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_aiv_pdf'),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export", export_aiv_csv, name='export_aiv_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteAIVCriterion, name="delete_aiv_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-aiv-rating/<int:ID>", DeleteAIVRating, name="delete_aiv_rating"),
    path("<slug:SEM>/<slug:SY>/aiv-rating-entry/", AIVRatingEntry.as_view(), name="aiv_rating_entry"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_aiv_eval_scores"),
    path("<slug:SEM>/<slug:SY>/new-aiv-evaluation/<int:ID>", NewAIVEvaluation, name="new_aiv_evaluation"),
    path("<slug:SEM>/<slug:SY>/aiv-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/facultyeval/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("member.urls")),
    path('administrator/', include("administrator.urls")),
    path('administrator/hr/', include("hr.urls")),
    path('administrator/canvas/', include("canvas.urls")),
    path('administrator/aiv/', include('aiv.urls')),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facultyeval/hr/urls.py
from django.urls import path
from .views import *

app_name = "hr"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_hr_pdf'),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export", export_hr_csv, name='export_hr_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteHRCriterion, name="delete_hr_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-hr-rating/<int:ID>", DeleteHRRating, name="delete_hr_rating"),
    path("<slug:SEM>/<slug:SY>/hr-rating-entry/", HRRatingEntry.as_view(), name="hr_rating_entry"), # <- This might not be used anymore
    path("<slug:SEM>/<slug:SY>/new-hr-evaluation/<int:ID>", NewHREvaluation, name="new_hr_evaluation"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_hr_eval_scores"),
    path("<slug:SEM>/<slug:SY>/hr-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/aiv/models.py
from django.db import models
from accounts.models import Member
from administrator.models import SchoolYear

# Create your models here.
class AIVRating(models.Model):
    FIRST_SEM = '1st-Sem'
    SECOND_SEM = '2nd-Sem'
    SEMESTER_CHOICES = [
        (FIRST_SEM, 'First Semester'),
        (SECOND_SEM, 'Second Semester')
    ]
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    school_year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)
    semester = models.CharField(max_length=200, choices=SEMESTER_CHOICES, default=FIRST_SEM)
    def __str__(self):
        return f"{self.member} - {self.school_year} - {self.semester}"

class AIVCriterion(models.Model):
    title = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.title}"

class AIVCriterionScores(models.Model):
    aivrating = models.ForeignKey(AIVRating, on_delete=models.CASCADE)
    aivcriterion = models.ForeignKey(AIVCriterion, on_delete=models.CASCADE)
    first_visit = models.FloatField(blank=True, null=True)
    second_visit = models.FloatField(blank=True, null=True)
    average_score = models.FloatField(blank=True , null=True)
    remarks = models.CharField(max_length=200)
    def __str__(self):
        return f"{self.aivrating} - {self.aivcriterion} - {self.first_visit} - {self.second_visit} - {self.average_score} - {self.remarks}"

facultyeval/aiv/forms.py
from django import forms
from .models import *

class AIVRatingForm(forms.ModelForm):

    class Meta:

        model = AIVRating
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AIVRatingForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({"name": field, "class": "form-control"})

class AIVCriterionScoresForm(forms.Form):

    first_visit = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    second_visit = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    average_score = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    remarks = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': "form-control"}))

class AIVCriterionForm(forms.ModelForm):

    class Meta:
        model = AIVCriterion
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AIVCriterionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({"name": field, "class": "form-control"})

facultyeval/aiv/views.py
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from accounts.models import Member
from django.contrib import messages
from .models import *
from .decorators import *
from .forms import *
from administrator.models import ActivityLogs
from django.http import HttpResponse
import csv
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import View
from django.template.loader import render_to_string
from django.conf import settings
import os

class RedirectIndex(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        SEM = "1st-Sem"
        try:
            _SY = SchoolYear.objects.latest("id")
            SY = _SY.school_year
            return redirect("aiv:index", SEM=SEM, SY=SY)
        except:
            pass
        messages.error(request, "School year does not exist!")
        return redirect("administrator:dashboard")

# Create your views here.
class Index(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY):
        members = Member.objects.all()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        sy_group = SchoolYear.objects.all()
        context = {"aiv_data": [], "SEM": SEM, "SY":SY, "sy_group": sy_group}
        for member in members:
            result = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM)
            if result.exists():
                context["aiv_data"].append([member, True])
                continue
            context["aiv_data"].append([member, False])
        return render(request, template_name="aiv/index.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY):
        return redirect("/")

class EvalScores(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY, ID):
        member = Member.objects.filter(id=ID).first()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
        aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating).all()
        context = {
            "aivcriterionscores": aivcriterionscores,
            "member_id": ID,
            "SY": SY,
            "SEM": SEM
        }
        return render(request, template_name="aiv/updateaivevalscores.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY, ID):
        return redirect("/")

class CriterionScores(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY, ID, CRITERIONID):
        member = Member.objects.filter(id=ID).first()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
        aivcriterion = AIVCriterion.objects.filter(id=CRITERIONID).first()
        aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating, aivcriterion=aivcriterion)
        if aivcriterionscores.exists():
            result = aivcriterionscores.first()
            form = AIVCriterionScoresForm(initial={
                "first_visit": result.first_visit,
                "second_visit": result.second_visit,
                "average_score": result.average_score,
                "remarks": result.remarks
            })
        else:
            form = AIVCriterionScoresForm()
        return render(request, template_name="aiv/criterionscores.html", context={"form": form})

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY, ID, CRITERIONID):
        form = AIVCriterionScoresForm(request.POST)
        if form.is_valid():
            member = Member.objects.filter(id=ID).first()
            school_year = SchoolYear.objects.filter(school_year=SY).first()
            aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
            aivcriterion = AIVCriterion.objects.filter(id=CRITERIONID).first()
            aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating, aivcriterion=aivcriterion)
            aivcriterionscores.update(**form.cleaned_data)
            messages.success(request, "Successfully updated criterion scores!")
        else:
            messages.error(request, "Error encountered updating criterion scores!")
        return redirect("aiv:update_aiv_eval_scores", SEM=SEM, SY=SY, ID=ID)

class ListOfCriteria(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        criteria = AIVCriterion.objects.all()
        form = AIVCriterionForm()
        context = {
            "criteria": criteria,
            "form": form
        }
        return render(request, template_name="aiv/listofcriteria.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request):
        # New criterion form
        if 'new_criterion' in request.POST:
            form = AIVCriterionForm(request.POST)
            if form.is_valid():
                aivcriterion = form.save(commit=False)
                title = form.cleaned_data.get('title')
                if AIVCriterion.objects.filter(title=title).exists():
                    messages.error(request, "AIV evaluation criterion already exist!")
                    return redirect("aiv:list_of_criteria")
                aivcriterion.save()
                messages.success(request, "AIV evaluation criterion successfully created!")
                return redirect("aiv:list_of_criteria")
        return redirect("/")

@login_required(login_url="accounts:login")
@admin_only
def DeleteAIVCriterion(request, ID):
    aivcriterion = AIVCriterion.objects.filter(id=ID)
    if aivcriterion.exists():
        aivcriterion.delete()
        messages.success(request, "AIV evaluation criterion was successfully deleted!")
        return redirect("aiv:list_of_criteria")
    else:
        messages.error(request, f"ID {ID} does not exist!")
    return redirect("aiv:list_of_criteria")

class AIVRatingEntry(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY):
        form = AIVRatingForm()
        context = {"form": form}
        return render(request, template_name="aiv/aivrating.html", context=context)
    
    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY):
        form = AIVRatingForm(request.POST)
        if form.is_valid():
            aivrating = form.save(commit=False)
            member = form.cleaned_data.get("member")
            semester = form.cleaned_data.get("semester")
            school_year = form.cleaned_data.get("school_year")
            if AIVRating.objects.filter(member=member, semester=semester, school_year=school_year).exists():
                messages.error(request, "AIV evaluation entry already exist!")
                return redirect("aiv:aiv_rating_entry", SEM=semester, SY=school_year)
            aivrating.save()
            criteria = AIVCriterion.objects.all()
            for criterion in criteria:
                criterion_scores = AIVCriterionScores(aivrating=aivrating, aivcriterion=criterion)
                criterion_scores.save()
            messages.success(request, "AIV evaluation entry successfully created!")
            return redirect("aiv:index", SEM=semester, SY=school_year)
        return redirect("aiv:aiv_rating_entry", SEM=SEM, SY=SY)

@login_required(login_url="accounts:login")
@admin_only
def DeleteAIVRating(request, SEM, SY, ID):
    member = Member.objects.filter(id=ID).first()
    school_year = SchoolYear.objects.filter(school_year=SY).first()
    aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM)
    if aivrating.exists():
        aivrating.delete()
        messages.success(request, "AIV evaluation entry was successfully deleted!")
        #ActivityLogs
        logs = ActivityLogs(member=member, activity_log=ActivityLogs.DELETED, eval_log=ActivityLogs.AIV)
        logs.save()
        # End of ActivityLogs
        return redirect("aiv:index", SEM=SEM, SY=SY)
    else:
        messages.error(request, f"ID {ID} does not exist!")
    return redirect("aiv:index", SEM=SEM, SY=SY)

@login_required(login_url="accounts:login")
@admin_only
def NewAIVEvaluation(request, SEM, SY, ID):
    member = Member.objects.filter(id=ID).first()
    school_year = SchoolYear.objects.filter(school_year=SY).first()
    if AIVRating.objects.filter(member=member, semester=SEM, school_year=school_year).exists():
        messages.error(request, "AIV evaluation entry already exist!")
        return redirect("aiv:index", SEM=SEM, SY=school_year)
    aivrating = AIVRating(member=member, semester=SEM, school_year=school_year)
    aivrating.save()
    criteria = AIVCriterion.objects.all()
    for criterion in criteria:
        criterion_scores = AIVCriterionScores(aivrating=aivrating, aivcriterion=criterion)
        criterion_scores.save()
    messages.success(request, "AIV evaluation entry successfully created!")
    #ActivityLogs

facultyeval/aiv/templates/aiv/aivrating.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %}Evaluation Form Criteria{% endblock %}
{% block nav_item_aiv %}active{% endblock %}
{% block content %}
<div style="padding: 50px; min-height: 100vh;">
    <!-- Title -->
    <div class="row">
        <div class="col">
            <h4 class="text-center">New AIV Evaluation</h4>
        </div>
    </div>
    <!-- Display messages from the server -->
    <div class="row">
        <div class="col">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                        {% if message.tags == 'error' %}<strong>Error Encountered!</strong><br>{% endif %}
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form class="form-group" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="d-grid" style="padding-top: 20px;">
                    <input class="btn btn-primary"type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

facultyeval/aiv/templates/aiv/index.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %}Faculty Evaluation in AIV{% endblock %}
{% block nav_item_aiv %}active{% endblock %}
{% block content %}
<div style="padding: 50px;min-height: 100vh;">
    <div class="row" style="margin-bottom: 20px;">
        <div class="col">
            <h3 class="text-center">ACADEMIC IMPROVEMENT VISITATION EVALUATION</h3>
        </div>
        <hr>
    </div>
    <div class="row" style="margin-bottom: 25px;">
        <div class="col d-flex justify-content-start text-center">
            <div class="dropdown">
                <a class="btn btn-primary dropdown-toggle border" href="#" role="button" id="schoolYearDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ SY }}
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="schoolYearDropdown">
                    {% for sy in sy_group %}
                        <li><a class="dropdown-item {% if SY == sy.school_year %}active{% endif %}" href="{% url 'aiv:index' SEM=SEM SY=sy.school_year %}">{{ sy.school_year }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="dropdown" style="margin-left: 10px;">
                <a class="btn btn-primary dropdown-toggle border" href="#" role="button" id="semesterDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if SEM == '1st-Sem' %}
                        1st Semester
                    {% elif SEM == '2nd-Sem' %}
                        2nd Semester
                    {% endif %}
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="semesterDropdown">
                    <li><a class="dropdown-item {% if SEM == '1st-Sem' %}active{% endif %}" href="{% url 'aiv:index' SEM='1st-Sem' SY=SY %}">1st Semester</a></li>
                    <li><a class="dropdown-item {% if SEM == '2nd-Sem' %}active{% endif %}" href="{% url 'aiv:index' SEM='2nd-Sem' SY=SY %}">2nd Semester</a></li>
                </ul>
            </div>
        </div>
        <div class="col d-flex justify-content-end">
            <a href= "{% url 'aiv:list_of_criteria' %}" class="btn btn-secondary">
                List of Criteria
            </a>
        </div>
    </div>
    <!-- Display messages from the server -->
    <div class="row">
        <div class="col">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                        {% if message.tags == 'error' %}<strong>Error Encountered!</strong><br>{% endif %}
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <!-- Display performance evaluation of each faculty member -->
    <div class="row">
        <div class="col">
            <table class="table table-hover border" id="myTable">
                <thead class="table-primary">
                    <th class="text-center" scope="col">FACULTY MEMBER</th>
                    <th class="text-center" scope="col">STATUS</th>
                    <th class="text-center">ACTIONS</th>
                </thead>
                <tbody>
                    {% for item in aiv_data %}
                        <tr scope="row">
                            <td class="text-center" scope="col" style="width: 40%;">
                                <img src="{% if item.0.image != '' %}/media/{{item.0.image}}{% else %}{% static 'img/profile_default.png' %}{% endif %}" class="rounded-circle" alt="" width="32" height="32">
                                {{item.0.user.last_name}}, {{item.0.user.first_name}}{% if item.0.middle_name != "" %}, {{item.0.middle_name}}{% endif %}
                            </td>
                            <td class="text-center" scope="col" style="width: 15%">
                                {% if item.1 == True %}
                                <img class="" src="{% static 'img/bootstrap/check-circle-fill.svg' %}" alt="check-circle"/>
                                {% else %}
                                <img src="{% static 'img/bootstrap/x-circle-fill.svg' %}" alt="x-circle"/>
                                {% endif %}
                            </td>
                            {% if item.1 == True %}
                            <td class="text-center" scope="col" style="width: 15%;">
                                <a href="{% url 'aiv:update_aiv_eval_scores' SEM=SEM SY=SY ID=item.0.id %}" class="btn" style="background-color: lightgreen;">
                                    <img id="user-icon" src="{% static 'img/bootstrap/pencil-square.svg' %}">
                                </a>
                                <a href="{% url 'aiv:delete_aiv_rating' SEM=SEM SY=SY ID=item.0.id%}" class="btn btn-danger">
                                    <img id="user-icon" src="{% static 'img/bootstrap/trash3-fill.svg' %}">
                                </a>
                            </td>
                            {% else %}
                            <td class="text-center" style="width: 15%;">
                                <a href="{% url 'aiv:new_aiv_evaluation' SEM=SEM SY=SY ID=item.0.id %}" class="btn btn-primary">New</a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

facultyeval/aiv/templates/aiv/listofcriteria.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %}List of Criteria{% endblock %}
{% block nav_item_aiv %}active{% endblock %}
{% block content %}
<div style="padding: 50px; min-height: 100vh;">
    <div class="row" style="margin-bottom: 25px;">
        <div class="col">
            <h3 class="text-center">LIST OF CRITERIA IN AIV EVALUATION</h3>
            <hr>
        </div>
    </div>
    <div class="row" style="margin-bottom: 25px;">
        <div class="col d-flex justify-content-end">
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newcriterion">New Criterion</button>
            <form method="POST">
                {% csrf_token %}
                <!-- Modal -->
                <div class="modal fade" id="newcriterion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">New Criterion</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {{ form }}
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success" name="new_criterion">Save</button>
                        </div>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Display messages from the server -->
    <div class="row">
        <div class="col">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                        {% if message.tags == 'error' %}<strong>Error Encountered!</strong><br>{% endif %}
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <!-- Display the criterion of the a specified criterion group -->
    <div class="row">
        <div class="col">
            <table class="table table-hover border" id="myTable">
                <thead class="table-primary">
                    <th class="text-center" scope="col">TITLE</th>
                    <th class="text-center" scope="col" style="width: 20%;">ACTIONS</th>
                </thead>
                <tbody>
                    {% for criterion in criteria %}
                        <tr scope="row">
                            <td class="text-center" scope="col">{{ criterion.title }}</td>
                            <td class="text-center" scope="col">
                                <a href="{% url 'aiv:delete_aiv_criterion' ID=criterion.id%}" class="btn btn-danger">
                                    <img id="user-icon" src="{% static 'img/bootstrap/trash3-fill.svg' %}">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- Modal -->
            <div class="modal fade" id="updatecriterion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update Criterion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success" name="update_criterion">Update</button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

facultyeval/aiv/templates/aiv/updateaivevalscores.html
{% extends 'administrator/base.html' %}
{% load static %}
{% block title %}HR Evaluation Crieria Form{% endblock %}
{% block nav_item_aiv %}active{% endblock %}
{% block content %}
<div style="padding: 50px; min-height: 100vh;">
    <!-- Title -->
    <div class="row">
        <div class="col">
            <h4 class="text-center">AIV Criteria Scores</h4>
            <hr>
        </div>
    </div>
    <div class="row" style="margin-bottom: 25px;">
        <div class="col">
            <a href="{% url 'aiv:export_aiv_pdf' SEM=SEM SY=SY ID=member_id %}" class="btn btn-warning" style="margin-right: 5px;">
                PDF
            </a>
            <a href="{% url 'aiv:export_aiv_csv' SEM=SEM SY=SY ID=member_id %}" class="btn btn-success">
                CSV
            </a>
        </div>
    </div>
    <!-- Display messages from the server -->
    <div class="row">
        <div class="col">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                        {% if message.tags == 'error' %}<strong>Error Encountered!</strong><br>{% endif %}
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-hover border">
                <thead class="table-danger">
                    <th class="text-center" scope="col">Criterion</th>
                    <th class="text-center" scope="col">First Visit</th>
                    <th class="text-center" scope="col">Second Visit</th>
                    <th class="text-center" scope="col">Average</th>
                    <th class="text-center" scope="col">Remarks</th>
                    <th class="text-center" scope="col">Actions</th>
                </thead>
                <tbody>
                    {% for item in aivcriterionscores %}
                        <tr scope="row">
                            <td class="text-center" scope="col" style="width: 25%">{{ item.aivcriterion.title }}</td>
                                <td class="text-center" scope="col" style="width: 15%">
                                    {% if item.first_visit is not None %}
                                        {{ item.first_visit }}
                                    {% endif %}
                                </td>
                            <td class="text-center" scope="col" style="width: 15%">
                                {% if item.second_visit is not None %}
                                    {{ item.second_visit }}
                                {% endif %}
                            </td>
                            <td class="text-center" scope="col" style="width: 15%">
                                {% if item.average_score is not None %}
                                    {{ item.average_score }}
                                {% endif %} 
                            </td>
                            <td class="text-center" scope="col" style="width: 10%">
                                {{ item.remarks }}
                            </td>
                            <td class="text-center" scope="col" style="width: 30%">
                                <a href="{% url 'aiv:criterion_scores' SY=SY SEM=SEM ID=member_id CRITERIONID=item.aivcriterion.id %}" class="btn" style="background-color: lightgreen;">
                                    <img id="user-icon" src="{% static 'img/bootstrap/pencil-square.svg' %}">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}