facultyeval/accounts/urls.py
from django.urls import path, reverse_lazy
from .views import Login, Register, logoutUser, PassResetView
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", logoutUser, name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("password-reset/", 
        PassResetView.as_view(
            template_name="accounts/reset_password.html",
            success_url=reverse_lazy("accounts:password_reset_done"),
            html_email_template_name="accounts/password_reset.html",
            email_template_name="accounts/password_reset.html"),
        name="password_reset"
    ),
    path("password-reset-done/", 
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/reset_password_done.html"), 
        name="password_reset_done"
    ),
    path("password-reset-confirm/<uidb64>/<token>/", 
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/reset_password_confirm.html", 
            success_url=reverse_lazy("accounts:password_reset_complete")),
        name="password_reset_confirm"
    ),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"), name="password_reset_complete"),
]

facultyeval/aiv/urls.py
from django.urls import path
from .views import *

app_name = "aiv"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_aiv_pdf'),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/export", export_aiv_csv, name='export_aiv_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteAIVCriterion, name="delete_aiv_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-aiv-rating/<int:ID>", DeleteAIVRating, name="delete_aiv_rating"),
    path("<slug:SEM>/<slug:SY>/aiv-rating-entry/", AIVRatingEntry.as_view(), name="aiv_rating_entry"),
    path("<slug:SEM>/<slug:SY>/update-aiv-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_aiv_eval_scores"),
    path("<slug:SEM>/<slug:SY>/new-aiv-evaluation/<int:ID>", NewAIVEvaluation, name="new_aiv_evaluation"),
    path("<slug:SEM>/<slug:SY>/aiv-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/facultyeval/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("member.urls")),
    path('administrator/', include("administrator.urls")),
    path('administrator/hr/', include("hr.urls")),
    path('administrator/canvas/', include("canvas.urls")),
    path('administrator/aiv/', include('aiv.urls')),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facultyeval/hr/urls.py
from django.urls import path
from .views import *

app_name = "hr"
urlpatterns = [
    path("", RedirectIndex.as_view(), name="redirect_index"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export_pdf", GeneratePdf.as_view(), name='export_hr_pdf'),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/export", export_hr_csv, name='export_hr_csv'),
    path("list-of-criteria/", ListOfCriteria.as_view(), name="list_of_criteria"),
    path("delete-criterion/<int:ID>/", DeleteHRCriterion, name="delete_hr_criterion"),
    path("<slug:SEM>/<slug:SY>/", Index.as_view(), name="index"),
    path("<slug:SEM>/<slug:SY>/delete-hr-rating/<int:ID>", DeleteHRRating, name="delete_hr_rating"),
    path("<slug:SEM>/<slug:SY>/hr-rating-entry/", HRRatingEntry.as_view(), name="hr_rating_entry"), # <- This might not be used anymore
    path("<slug:SEM>/<slug:SY>/new-hr-evaluation/<int:ID>", NewHREvaluation, name="new_hr_evaluation"),
    path("<slug:SEM>/<slug:SY>/update-hr-eval-scores/<int:ID>/", EvalScores.as_view(), name="update_hr_eval_scores"),
    path("<slug:SEM>/<slug:SY>/hr-eval-scores/criterion-scores/<int:ID>/<int:CRITERIONID>/", CriterionScores.as_view(), name="criterion_scores")
]

facultyeval/member/urls.py
from django.urls import path
from .views import *

app_name = "member"
urlpatterns = [
    path("", Home, name="home"),
    path("profile/", Profile, name="profile"),
    path("profile/edit/", EditProfile.as_view(), name="edit_profile"),
    path("hr/", HR, name="hr"),
    path("hr/eval-scores/<slug:SEM>/<slug:SY>/", HREvalScores, name="hr_eval_scores"),
    path("aiv/", AIV, name="aiv"),
    path("aiv/eval-scores/<slug:SEM>/<slug:SY>", AIVEvalScores, name="aiv_eval_scores"),
    path("lms/<slug:SEM>/<slug:SY>/", LMS, name="lms"),
    path("lms/", RedirectLMS, name="redirect_lms"),
    path("about/", About, name="about"),
    path("hr/eval-scores/<slug:SEM>/<slug:SY>/export_pdf", GeneratePdfHR.as_view(), name='export_hr_pdf'),
    path("hr/eval-scores/<slug:SEM>/<slug:SY>/export", export_hr_csv, name='export_hr_csv'),
    path("aiv/eval-scores/<slug:SEM>/<slug:SY>/export_pdf", GeneratePdfAIV.as_view(), name='export_aiv_pdf'),
    path("aiv/eval-scores/<slug:SEM>/<slug:SY>/export", export_aiv_csv, name='export_aiv_csv')
]

facultyeval/member/models.py
from django.db import models

# Create your models here.

facultyeval/aiv/forms.py
from django import forms
from .models import *

class AIVRatingForm(forms.ModelForm):

    class Meta:

        model = AIVRating
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AIVRatingForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({"name": field, "class": "form-control"})

class AIVCriterionScoresForm(forms.Form):

    first_visit = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    second_visit = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    average_score = forms.FloatField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    remarks = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': "form-control"}))

class AIVCriterionForm(forms.ModelForm):

    class Meta:
        model = AIVCriterion
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AIVCriterionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
            self.fields[field].widget.attrs.update({"name": field, "class": "form-control"})

facultyeval/member/forms.py
from django import forms
from accounts.models import *
from django.contrib.auth.models import User

class EditUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({"class": "form-control"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control"})
        self.fields["email"].widget.attrs.update({"class": "form-control"})

class EditMemberForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = ["middle_name", "image"]

    def __init__(self, *args, **kwargs):
        super(EditMemberForm, self).__init__(*args, **kwargs)
        self.fields["middle_name"].widget.attrs.update({"class":"form-control"})
        self.fields["image"].widget.attrs.update({"type": "file", "class":"form-control"})

facultyeval/aiv/views.py
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from accounts.models import Member
from django.contrib import messages
from .models import *
from .decorators import *
from .forms import *
from administrator.models import ActivityLogs
from django.http import HttpResponse
import csv
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import View
from django.template.loader import render_to_string
from django.conf import settings
import os

class RedirectIndex(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        SEM = "1st-Sem"
        try:
            _SY = SchoolYear.objects.latest("id")
            SY = _SY.school_year
            return redirect("aiv:index", SEM=SEM, SY=SY)
        except:
            pass
        messages.error(request, "School year does not exist!")
        return redirect("administrator:dashboard")

# Create your views here.
class Index(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY):
        members = Member.objects.all()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        sy_group = SchoolYear.objects.all()
        context = {"aiv_data": [], "SEM": SEM, "SY":SY, "sy_group": sy_group}
        for member in members:
            result = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM)
            if result.exists():
                context["aiv_data"].append([member, True])
                continue
            context["aiv_data"].append([member, False])
        return render(request, template_name="aiv/index.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY):
        return redirect("/")

class EvalScores(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY, ID):
        member = Member.objects.filter(id=ID).first()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
        aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating).all()
        context = {
            "aivcriterionscores": aivcriterionscores,
            "member_id": ID,
            "SY": SY,
            "SEM": SEM
        }
        return render(request, template_name="aiv/updateaivevalscores.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY, ID):
        return redirect("/")

class CriterionScores(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY, ID, CRITERIONID):
        member = Member.objects.filter(id=ID).first()
        school_year = SchoolYear.objects.filter(school_year=SY).first()
        aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
        aivcriterion = AIVCriterion.objects.filter(id=CRITERIONID).first()
        aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating, aivcriterion=aivcriterion)
        if aivcriterionscores.exists():
            result = aivcriterionscores.first()
            form = AIVCriterionScoresForm(initial={
                "first_visit": result.first_visit,
                "second_visit": result.second_visit,
                "average_score": result.average_score,
                "remarks": result.remarks
            })
        else:
            form = AIVCriterionScoresForm()
        return render(request, template_name="aiv/criterionscores.html", context={"form": form})

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY, ID, CRITERIONID):
        form = AIVCriterionScoresForm(request.POST)
        if form.is_valid():
            member = Member.objects.filter(id=ID).first()
            school_year = SchoolYear.objects.filter(school_year=SY).first()
            aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM).first()
            aivcriterion = AIVCriterion.objects.filter(id=CRITERIONID).first()
            aivcriterionscores = AIVCriterionScores.objects.filter(aivrating=aivrating, aivcriterion=aivcriterion)
            aivcriterionscores.update(**form.cleaned_data)
            messages.success(request, "Successfully updated criterion scores!")
        else:
            messages.error(request, "Error encountered updating criterion scores!")
        return redirect("aiv:update_aiv_eval_scores", SEM=SEM, SY=SY, ID=ID)

class ListOfCriteria(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request):
        criteria = AIVCriterion.objects.all()
        form = AIVCriterionForm()
        context = {
            "criteria": criteria,
            "form": form
        }
        return render(request, template_name="aiv/listofcriteria.html", context=context)

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request):
        # New criterion form
        if 'new_criterion' in request.POST:
            form = AIVCriterionForm(request.POST)
            if form.is_valid():
                aivcriterion = form.save(commit=False)
                title = form.cleaned_data.get('title')
                if AIVCriterion.objects.filter(title=title).exists():
                    messages.error(request, "AIV evaluation criterion already exist!")
                    return redirect("aiv:list_of_criteria")
                aivcriterion.save()
                messages.success(request, "AIV evaluation criterion successfully created!")
                return redirect("aiv:list_of_criteria")
        return redirect("/")

@login_required(login_url="accounts:login")
@admin_only
def DeleteAIVCriterion(request, ID):
    aivcriterion = AIVCriterion.objects.filter(id=ID)
    if aivcriterion.exists():
        aivcriterion.delete()
        messages.success(request, "AIV evaluation criterion was successfully deleted!")
        return redirect("aiv:list_of_criteria")
    else:
        messages.error(request, f"ID {ID} does not exist!")
    return redirect("aiv:list_of_criteria")

class AIVRatingEntry(View):

    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def get(self, request, SEM, SY):
        form = AIVRatingForm()
        context = {"form": form}
        return render(request, template_name="aiv/aivrating.html", context=context)
    
    @method_decorator(login_required(login_url="accounts:login"))
    @method_decorator(admin_only)
    def post(self, request, SEM, SY):
        form = AIVRatingForm(request.POST)
        if form.is_valid():
            aivrating = form.save(commit=False)
            member = form.cleaned_data.get("member")
            semester = form.cleaned_data.get("semester")
            school_year = form.cleaned_data.get("school_year")
            if AIVRating.objects.filter(member=member, semester=semester, school_year=school_year).exists():
                messages.error(request, "AIV evaluation entry already exist!")
                return redirect("aiv:aiv_rating_entry", SEM=semester, SY=school_year)
            aivrating.save()
            criteria = AIVCriterion.objects.all()
            for criterion in criteria:
                criterion_scores = AIVCriterionScores(aivrating=aivrating, aivcriterion=criterion)
                criterion_scores.save()
            messages.success(request, "AIV evaluation entry successfully created!")
            return redirect("aiv:index", SEM=semester, SY=school_year)
        return redirect("aiv:aiv_rating_entry", SEM=SEM, SY=SY)

@login_required(login_url="accounts:login")
@admin_only
def DeleteAIVRating(request, SEM, SY, ID):
    member = Member.objects.filter(id=ID).first()
    school_year = SchoolYear.objects.filter(school_year=SY).first()
    aivrating = AIVRating.objects.filter(member=member, school_year=school_year, semester=SEM)
    if aivrating.exists():
        aivrating.delete()
        messages.success(request, "AIV evaluation entry was successfully deleted!")
        #ActivityLogs
        logs = ActivityLogs(member=member, activity_log=ActivityLogs.DELETED, eval_log=ActivityLogs.AIV)
        logs.save()
        # End of ActivityLogs
        return redirect("aiv:index", SEM=SEM, SY=SY)
    else:
        messages.error(request, f"ID {ID} does not exist!")
    return redirect("aiv:index", SEM=SEM, SY=SY)

@login_required(login_url="accounts:login")
@admin_only
def NewAIVEvaluation(request, SEM, SY, ID):
    member = Member.objects.filter(id=ID).first()
    school_year = SchoolYear.objects.filter(school_year=SY).first()
    if AIVRating.objects.filter(member=member, semester=SEM, school_year=school_year).exists():
        messages.error(request, "AIV evaluation entry already exist!")
        return redirect("aiv:index", SEM=SEM, SY=school_year)
    aivrating = AIVRating(member=member, semester=SEM, school_year=school_year)
    aivrating.save()
    criteria = AIVCriterion.objects.all()
    for criterion in criteria:
        criterion_scores = AIVCriterionScores(aivrating=aivrating, aivcriterion=criterion)
        criterion_scores.save()
    messages.success(request, "AIV evaluation entry successfully created!")
    #ActivityLogs

facultyeval/member/templates/member/aiv.html
{% extends 'member/base.html' %}
{% load static %}
{% block title %}Faculty Evaluation in AIV{% endblock %}
{% block nav_item_aiv %}active{% endblock %}
{% block content %}
<div style="padding: 50px; min-height: 100vh; background-color:azure;">
    <div class="row">
        <div class="col">
            <h3 class="text-center">FACULTY EVALUATION BY AIV</h3>
            <hr>
        </div>
    </div>
    <!-- Display performance evaluation of each faculty member -->
    <div class="row">
        <div class="col">
            <table class="table table-hover border" id="myTable">
                <thead class="table-primary">
                    <th class="text-center" scope="col">SCHOOL YEAR</th>
                    <th class="text-center" scope="col">SEMESTER</th>
                    <th class="text-center">ACTIONS</th>
                </thead>
                <tbody>
                    {% for aivrating in aivratings %}
                        <tr scope="row">
                            <td class="text-center" scope="col" style="width: 20%;">{{ aivrating.school_year }}</td>
                            <td class="text-center" scope="col" style="width: 20%">{{ aivrating.semester }}</td>
                            <td class="text-center" scope="col" style="width: 15%;">
                                <a href="{% url 'member:aiv_eval_scores' SEM=aivrating.semester SY=aivrating.school_year %}" class="btn" style="background-color: lightgreen;">
                                    <img id="user-icon" src="{% static 'img/bootstrap/pencil-square.svg' %}">
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

facultyeval/member/templates/member/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.css"/>
    </head>
    <body>
        <div class="container-fluid" style="position: absolute; padding-left: 0rem;">
            <div class="row">
                <!-- Sidebar Navigation -->
                <div class="col-auto" style="padding-right: 0rem;">
                    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px; height: 100vh; position:fixed;">
                        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                          <span class="fs-4">Faculty Evaluation</span>
                        </a>
                        <hr>
                        <ul class="nav nav-pills flex-column mb-auto">
                            <li class="nav-item">
                                <a href="{% url 'member:home' %}" class="nav-link {% block nav_item_home %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/house-fill.svg'%}" style = "filter:invert(100%)" />
                                  Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'member:hr' %}" class="nav-link {% block nav_item_hr %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/journals.svg'%}" />
                                  HR
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'member:aiv' %}" class="nav-link {% block nav_item_aiv %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/clipboard-data-fill.svg'%}" />
                                  AIV
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'member:redirect_lms' %}" class="nav-link {% block nav_item_lms %}{% endblock %} text-white">
                                  <img src = "{% static 'img/bootstrap/mortarboard-fill.svg'%}" /> 
                                  LMS
                                </a>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown">
                            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                              <img src="{% if user.member.image != '' %}/media/{{user.member.image}}{% else %}{% static 'img/profile_default.png' %}{% endif %}" alt="" width="32" height="32" class="rounded-circle me-2">
                              <strong>{{user.username}}</strong>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                              <li><a class="dropdown-item" href="{% url 'member:profile' %}"> <img src = "{% static 'img/bootstrap/person-circle.svg'%}" /> Profile</a></li>
                              <li><a class="dropdown-item" href="{% url 'member:about' %}"> <img src = "{% static 'img/bootstrap/person-workspace.svg'%}" /> About</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"><img src = "{% static 'img/bootstrap/box-arrow-right.svg'%}" /> Sign out</a></li>
                            </ul>
                          </div>
                    </div>
                </div>
                <!-- Content -->
                <div class="col" style="margin-left: 280px;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <!-- Footer -->
            {% include 'administrator/footer.html' %}
        </div>
        <!-- JS Scripts -->
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% block javascript %}
        {% endblock %}
    </body>
</html>

facultyeval/member/templates/member/home.html
{% extends 'member/base.html' %}
{% block title %}Home{% endblock %}
{% block nav_item_home %}active{% endblock %}
{% block content %}
{% load static %}
<div class="row" style="min-height: 100vh; background-color:azure;">
    <div class="col d-flex justify-content-center">
        <div class="container">
            <div class="row my-5">
                <h4 class="text-left">Welcome {{user.username}}!</h4>
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video1" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/HR2.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">HR Evaluation</h5>
                            <p class="card-text">Navigate to HR panel to view HR evaluation.</p>
                            <a href="{% url 'member:hr' %}" class="btn btn-primary">Go to HR</a>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video2" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/AIV2.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">AIV Evaluation</h5>
                            <p class="card-text">Navigate to AIV panel to view AIV evaluation.</p>
                            <a href="{% url 'member:aiv' %}" class="btn btn-primary">Go to AIV</a>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div>
                            <video id="video3" class="card-img-top"
                                autoPlay data-play="hover" muted="muted">
                                <source src="{% static 'img/dashboard/LMS2.mp4' %}"
                                    type="video/mp4">
                                Your browser does not 
                                support the video tag.
                            </video>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">LMS Evaluation</h5>
                            <p class="card-text">Navigate to LMS panel to view LMS evaluation.</p>
                            <a href="{% url 'member:redirect_lms' %}" class="btn btn-primary">Go to LMS</a>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="my-5">
            <!-- Start of data table -->
            <div class="col d-flex justify-content-center">
                <div class="row">
                    <h5 class="text-left">Evaluation logs</h5>
                    <table class="table table-hover" id="myTable">
                        <thead class="table-primary">
                            <th class="text-center" scope="col">Evaluation</th>
                            <th class="text-center" scope="col">Status</th>
                            <th class="text-center" scope="col">Date/Time</th>
                        </thead>
                        <tbody>
                            {% for log in logs %}
                                <tr scope="row">
                                    <td class="text-center" scope="col" style="width: 20%;">{{log.eval_log}}</td>
                                    <td class="text-center" scope="col" style="width: 20%;">{{log.activity_log}}</td>
                                    <td class="text-center" scope="col" style="width: 20%;">{{log.date_log}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascript %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.js"></script>
<script>
	$(document).ready(function(){
		$('#myTable').DataTable();
	});
</script>
<script>
    // Getting video element using jQuery
    var video1 = $("#video1");
    var video2 = $("#video2");
    var video3 = $("#video3");
    // Check if video is ready to play
    $(video1).on('canplay', function () {
        $(video1).mouseenter(function () {
            $(this).get(0).play();
        })
    });
    $(video2).on('canplay', function () {
        $(video2).mouseenter(function () {
            $(this).get(0).play();
        })
    });
    $(video3).on('canplay', function () {
        $(video3).mouseenter(function () {
            $(this).get(0).play();
        })
    });    
</script>
{% endblock %}

facultyeval/member/templates/member/lmsevalscores.html
{% extends 'member/base.html' %}
{% load static %}
{% block title %}LMS Evaluation Scores{% endblock %}
{% block nav_item_lms %}active{% endblock %}
{% block content %}

{% endblock %}